// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

@freezed
sealed class FieldValue with _$FieldValue {
  const FieldValue._();

  const factory FieldValue.null_() = FieldValue_Null;
  const factory FieldValue.string(
    String field0,
  ) = FieldValue_String;
  const factory FieldValue.int(
    PlatformInt64 field0,
  ) = FieldValue_Int;
  const factory FieldValue.bool(
    bool field0,
  ) = FieldValue_Bool;
  const factory FieldValue.float(
    double field0,
  ) = FieldValue_Float;
  const factory FieldValue.array(
    List<FieldValue> field0,
  ) = FieldValue_Array;
}
